(require 'init-imp)
(require 'init-ag)
(require 'init-android)
(require 'init-autopair)
(require 'init-company)
(require 'init-dired)
(require 'init-docker)
(require 'init-flycheck)
(require 'init-git)
(require 'init-ivy)
(require 'init-js)
(require 'init-js-tide)
(require 'init-markdown)
(require 'init-modeline)
(require 'init-config-files)
(require 'init-org)
(require 'init-php)
(require 'init-projectile)
(require 'init-python)
(require 'init-python-jedi)
;; (require 'init-python-eglot)
(require 'init-rest)
(require 'init-ruby)
(require 'init-sudo)
(require 'init-scss)
(require 'init-ui)
(require 'init-web-mode)
(require 'init-whitespace-helpers)
(require 'init-winner)
(require 'init-yaml)

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
 '(erb-face ((((class color) (min-colors 88) (background dark)) (:background "#121212"))))
 '(erb-out-delim-face ((((background dark)) (:background "#121212" :foreground "#aaffff"))))
 '(header-line ((default (:inherit mode-line)) (((class color grayscale) (background light)) (:background "grey90" :foreground "grey20" :box nil))))
 '(link ((((class color) (min-colors 88) (background light)) (:foreground "blue1" :underline t))))
 '(mmm-code-submode-face ((t (:background "LightGray"))))
 '(mmm-default-submode-face ((t (:background "#111111"))))
 '(mumamo-background-chunk-major ((((class color) (min-colors 88) (background light)) (:background "black"))))
 '(mumamo-background-chunk-submode1 ((((class color) (min-colors 88) (background light)) (:background "#111111"))))
 '(mumamo-background-chunk-submode2 ((((class color) (min-colors 88) (background light)) (:background "dark violet"))))
 )

(provide 'init-all)
